version: '3'

services:
  server:
    build: .
    container_name: slice_backend
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - .:/app

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - server
