version: '3'

services:
  server:
    build: .
    container_name: slice_backend
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/src/app

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - server

  rabbitMQ:
    image: rabbitmq:latest
    container_name: rabbitmq
    ports:
      - "5672:5672"
    volumes:
      - .:/api

  celery:
    build: .
    container_name: celery_worker
    command: celery -A tasks worker 
    depends_on:
      - server
      - rabbitMQ
    volumes:
      - .:/usr/src/app
    environment:
      - CELERY_BROKER_URL=pyamqp://guest:guest@rabbitMQ:5672//
      - CELERY_RESULT_BACKEND=rpc://